name: Run Automation Script

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  schedule:
    - cron: "*/30 * * * *" # Runs every 30 minutes

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up jq
        run: sudo apt-get install -y jq

      - name: Run Automation Script
        env:
          USERNAME: ${{ secrets.USERNAME }}
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          RUN_NUMBER: ${{ github.run_number }}
        run: |
          chmod +x ./automation.sh
          ./automation.sh